### ISSUE TITLE
[680x0] bcc with address in absolute-short range yields source operand error

### ISSUE THREAD

**Issue by mikepavone** [asmotor/asmotor#15] opened 2022-04-16 21:01 UTC
The following code
```
	section "ROM", CODE[$0]
forever:
	bra forever
```
Produces the error `foo.s68:3: E0103 Invalid source operand`
I believe what is happening here is that `m68k_GetAddressingMode` does some optimization on the addressing mode and so a bare label like `forever` in this example gets transformed into `AM_WORD` if the value of the symbol is already known and within the valid range for absolute short. The instruction table entries for the bcc family only have AM_LONG in the valid addressing mode bitfield which results in an error when this optimization is done

Simplest fix is probably just to add AM_WORD as a valid addressing mode to the bcc family, but I'm not sure if that was omitted intentionally (perhaps to forbid an explicit `.w` for these instructions since it doesn't make sense)

**Comment by ghost** [comment] 2022-04-17 14:23
Thank you for reporting this, this is now fixed in 69c5846938d94a2c4dec7785ab221c27b551bcc8

This felt a lot like a regression, but it turns out this issue was previously observed with `DBcc`, which then included `AM_WORD` as a valid addressing mode as a quick fix. That was clearly not the right fix, as this allowed non-sensical code such as `DBRA d0,(.loop).L`.

The modes `AM_WORD` `(xxx).W` and `AM_LONG` `(xxx).L` are really not related to the `Bcc` and `DBcc` branch target operand and allowing the suffices don't make sense in the context of a PC-relative branch instruction. As the branch destination therefore seems like it's a special case addressing mode, parsing and handling of this mode has been moved to the `Bcc` and `DBcc` instructions, bypassing the address mode parser.

**Closed as completed** 2022-04-17 14:40 UTC
